config/routes.rb
Rails.application.routes.draw do
  resources :questions

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :news

  root 'main#index'

  get 'contacts' => 'main#contacts'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  text        :text
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_answers_on_question_id  (question_id)
#

class Answer < ActiveRecord::Base
  belongs_to :question

  validates_presence_of :text, :question_id
end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id         :integer          not null, primary key
#  title      :string
#  preview    :text
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class News < ActiveRecord::Base
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  author     :string
#  email      :string
#  published  :boolean          default(FALSE)
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  has_one :answer, dependent: :destroy
  accepts_nested_attributes_for :answer

  scope :published, -> {where published: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @news = News.all.limit(3)
  end

  def contacts

  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.published
    @question  = Question.new
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to questions_path, notice: 'Ваш вопрос получен!'
    else
      redirect_to questions_path, error: 'Корректно заполните все поля'
    end
  end


  private
    def question_params
      params.require(:question).permit :author, :text, :email
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title УК "Стандарт Плюс"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{src: "http://maps.api.2gis.ru/2.0/loader.js?pkg=full", 'data-turbolinks-track' => false}
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "/"} УК "Стандарт Плюс"
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            =# active_link_to 'Главная', '/', wrap_tag: 'li'
            = active_link_to 'Новости', news_index_path, wrap_tag: 'li'
            %li
              %a{:href => "portfolio.html"} Наши услуги
            %li
              %a{:href => "pricing.html"} Пункты приема платежей
            = active_link_to 'Вопрос-Ответ', questions_path, wrap_tag: 'li'
            = active_link_to 'Контакты', contacts_path, wrap_tag: 'li'
    / /.NAVBAR END

    - if content_for? :page_header
      %section#home.head-main-img
        .container
          .row.text-center.pad-row
            .col-md-12
              %h1
                = yield :page_header


    = yield

    %section.note-sec
      .container
        .row.text-center.pad-row
          .col-md-8.col-md-offset-2.col-sm-8.col-sm-offset-2
            %i.fa.fa-quote-left.fa-3x
            %p
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
    / /.NOTE END
    / /.CLIENTS END
    .grass-block
    %section#footer-sec
      .container
        .row.pad-bottom
          .col-md-4
            %h4
              %strong О компании
            %p
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            %a{:href => "#"} read more
          .col-md-4
          .col-md-4
            %h4
              %strong НАШ АДРЕС
            %p
              628406, Ханты-Мансийский Автономный округ - Югра АО,
              Сургут г,
              %br/
              Нижневартовское ш, дом № 11, строение 4
    / /.FOOTER END

app/views/main/contacts.html.slim
- content_for :page_header
  | Контакты
.container
  .col-md-6.wow.slideInLeft
    div id="map" style="width:500px; height:400px"
  .col-md-6.wow.slideInRight
    h3 Полезные контакты
    p Общество с Ограниченной Ответственностью «Управляющая компания «Стандарт Плюс»
    p
      b Юридический адрес: &nbsp;
      span 628406, Ханты-Мансийский Автономный округ - Югра АО, Сургут г, Нижневартовское ш, дом № 11, строение 4
    p
      b Фактический адрес: &nbsp;
      span  628406, Ханты-Мансийский Автономный округ - Югра АО, Сургут г, Нижневартовское ш, дом № 11, строение 4
    p
      b Тел.: &nbsp;
      span +7 904 471 2432
    p
      b Факс: &nbsp;
      span (3462) 555517
    p
      b Директор: &nbsp;
      span Солина Любовь Юрьевна


coffee:
  window.map2Gis()

app/views/main/index.html.haml
.custom-page-header
  .container
    .h1
      «Стандарт Плюс»
      %small
        | Управляющая компания

%section#intro
  .container
    .row.text-center
      .col-md-12
        .row.text-center.pad-row
          .col-md-4.col-sm-4
            %h3
              %strong Солина Любовь Юрьевна
            %p
              Директор
              %a{href: 'tel:71-24-32'} 71-24-32
          .col-md-4.col-sm-4
            %h3
              %strong Захаров Валерий Петрович
            %p
              Зам. директора
              %a{href: 'tel:71-20-15'} 71-20-15
          .col-md-4.col-sm-4
            %h3
              %strong Рябцевич Сергей Адамович
            %p
              Инженер
              %a{href: 'tel:71-20-17'} 71-20-17


          .col-md-4.col-sm-4
            %h3
              %strong Мастер жилищного фонда
            %p
              %a{href: 'tel:71-20-19'} 71-20-19
          .col-md-4.col-sm-4
            %h3
              %strong Тихомирова Лариса Александровна
            %p
              Паспортный стол
              %a{href: 'tel:26-43-70'} 26-43-70
          .col-md-4.col-sm-4
            %h3
              %strong Панамарева Татьяна Александровна&nbsp;
            %p
              Паспортный стол
              %a{href: 'tel:26-43-70'} 26-43-70



  //.INTRO END
  %section#offer
    .container
      .row.alert.alert-info
        .h1.text-center
          Круглосуточный телефон:
          %a{href: 'tel:+7(3462)71-24-33'} +7(3462)71-24-33

  / /.OFFFER END
  %section#just-intro
    .container
      .row.text-center.pad-row
        .col-md-4.col-sm-4
          %i.fa.fa-building.fa-5x
          %h4
            %strong Строим
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          //%a.btn.btn-primary{:href => "#"} Read Details
        .col-md-4.col-sm-4
          %i.fa.fa-wrench.fa-5x
          %h4
            %strong Чиним
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          //%a.btn.btn-primary{:href => "#"} Read Details
        .col-md-4.col-sm-4
          %i.fa.fa-plug.fa-5x
          %h4
            %strong Подключаем
          %p
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Curabitur nec nisl odio. Mauris vehicula at nunc id posuere.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          //%a.btn.btn-primary{:href => "#"} Read Details

app/views/main/index.html.slim
- content_for :header
  h1
    | «Стандарт Плюс»
    small
      | Управляющая компания

.container
  .col-md-6.wow.slideInLeft
    h3 Полезные контакты

    .contacts
      .contact
        .h4
          | Солина Любовь Юрьевна&nbsp;
          .small
            | Директор
        a href='tel:71-24-32' 71-24-32
      .contact
        .h4
          | Захаров Валерий Петрович&nbsp;
          .small
            | Зам. директора
        a href='tel:71-20-15' 71-20-15
      .contact
        .h4
          | Рябцевич Сергей Адамович&nbsp;
          .small
            | Инженер
        a href='tel:71-20-17' 71-20-17
      .contact
        .h4
          | Мастер жилищного фонда&nbsp;
        a href='tel:71-20-19' 71-20-19
      .contact
        .h4
          | Тихомирова Лариса Александровна&nbsp;
          .small
            | Паспортный стол
        a href='tel:26-43-70' 26-43-70
      .contact
        .h4
          | Панамарева Татьяна Александровна&nbsp;
          .small
            | Абонентский отдел
        a href='tel:26-43-70' 26-43-70
      .contact
        .h4
          | Информация о приеме показаний счетчиков:&nbsp;
        a href='tel:26-43-70' 26-43-70
  .col-md-6
    h3 Последние новости:
    .list-group
      - @news.each do |news|
        = link_to news, class: 'list-group-item wow bounceInRight'
          h4
            = news.title
            | &nbsp;
            small = news.created_at.strftime('%F')
          p
            = news.preview
.container
  .col-md-6.wow.slideInLeft
    h3 Реквизиты компании

  .col-md-6.wow.slideInRight
    h3 Часы работы
    p 8-17 выходной Суб.,Воскр.
    p Паспортный стол  пн.,вт.,чт.,пт. 9-12
.grass-block

app/views/main/index_old.html.slim
- content_for :header
  h1
    | «Стандарт Плюс»
    small
      | Управляющая компания

.container
  .col-md-6.wow.slideInLeft
    h3 Полезные контакты

    .contacts
      .contact
        .h4
          | Солина Любовь Юрьевна&nbsp;
          .small
            | Директор
        a href='tel:71-24-32' 71-24-32
      .contact
        .h4
          | Захаров Валерий Петрович&nbsp;
          .small
            | Зам. директора
        a href='tel:71-20-15' 71-20-15
      .contact
        .h4
          | Рябцевич Сергей Адамович&nbsp;
          .small
            | Инженер
        a href='tel:71-20-17' 71-20-17
      .contact
        .h4
          | Мастер жилищного фонда&nbsp;
        a href='tel:71-20-19' 71-20-19
      .contact
        .h4
          | Тихомирова Лариса Александровна&nbsp;
          .small
            | Паспортный стол
        a href='tel:26-43-70' 26-43-70
      .contact
        .h4
          | Панамарева Татьяна Александровна&nbsp;
          .small
            | Абонентский отдел
        a href='tel:26-43-70' 26-43-70
      .contact
        .h4
          | Информация о приеме показаний счетчиков:&nbsp;
        a href='tel:26-43-70' 26-43-70
  .col-md-6
    h3 Последние новости:
    .list-group
      - @news.each do |news|
        = link_to news, class: 'list-group-item wow bounceInRight'
          h4
            = news.title
            | &nbsp;
            small = news.created_at.strftime('%F')
          p
            = news.preview
.container
  .col-md-6.wow.slideInLeft
    h3 Реквизиты компании

  .col-md-6.wow.slideInRight
    h3 Часы работы
    p 8-17 выходной Суб.,Воскр.
    p Паспортный стол  пн.,вт.,чт.,пт. 9-12
.grass-block

app/views/news/index.html.slim
.page-header
  .container
    h1
      | Новости
.container
  .list-group
    - @news.each do |news|
      = link_to news, class: 'psudo-link wow slideInRight'
        h2
          = news.title
          | &nbsp;
          small = news.created_at.strftime('%F')
        p
          = news.preview

app/views/news/show.html.slim
.page-header
  .container
    h1
      | Новости

.container
  h2 = @news.title
  article
    = @news.text

app/views/questions/_form.html.slim
= form_for @question, html: {class: 'form-horizontal'} do |f|

  - if @question.errors.any?
    #error_explanation
      h2 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li = message
  .form-group
    .field
      = f.label :author
      = f.text_field :author, class: 'form-control'
    .field
      = f.label :email
      = f.text_field :email, type: :email, class: 'form-control'
    .field
      = f.label :text
      = f.text_area :text, class: 'form-control'
  .form-group.actions
    = f.submit 'Задать вопрос', class: 'btn btn-default'

app/views/questions/index.html.slim
.page-header
  .container
    h1
      | Вопрос-Ответ

.container
  - if flash[:notice]
    .alert.alert-success.wow.bounceInDown
      = flash[:notice]
  .media-list.questions
    - @questions.each do |q|
      .panel.panel-default.wow.slideInRight
        .panel-body
          .media.question
            .media-left
              i.fa.fa-question.fa-3x
            .media-body
              .h4.media-heading
                = q.text
              = q.author
              | &nbsp
              = q.created_at
              - if q.answer.present?
                .media
                  .media-left
                  .media-body
                    .h4.media-heading Ответ:
                    = q.answer.text

      /.question
      /  .body.clearfix
      /    .bubble
      /      = q.text
      /  - if q.answer.present?
      /    .answer.clearfix
      /      .bubble
      /        = q.answer.text

.container.wow.slideInLeft
  .h3
    | Задать вопрос:
  = render 'questions/form'